myhealthbanner_configuration_form_simple:
  path: /myhealthbanner/configuration
  methods: [GET, POST]
  defaults:
    _controller: 'PrestaShop\Module\MyHealthBanner\Controller\MyhealthbannerConfigurationController::index'
    # Needed to work with tab system
    _legacy_controller: AdminMyHealthBanner
    _legacy_link: AdminMyHealthBanner
