services:
  _defaults:
    public: true

  # Demo configuration text form
  prestashop.module.Myhealthbanner.form.type.Myhealthbanner_text:
    class: 'PrestaShop\Module\Myhealthbanner\Form\MyhealthbannerConfigurationFormType'
    parent: 'form.type.translatable.aware'
    public: true
    tags:
      - { name: form.type }
