services:
  _defaults:
    public: true

  # Demo configuration text form
  prestashop.module.myhealthbanner.form.type.myhealthbanner_text:
    class: 'PrestaShop\Module\Myhealthbanner\Form\MyhealthbannerConfigurationFormType'
    parent: 'form.type.translatable.aware'
    public: true
    tags:
      - { name: form.type }

  prestashop.module.myhealthbanner.form.myhealthbanner_text_data_configuration:
    class: 'PrestaShop\Module\Myhealthbanner\Form\MyhealthbannerTextDataConfiguration'
    arguments: [ '@prestashop.adapter.legacy.configuration' ]

  prestashop.module.myhealthbanner.form.myhealthbanner_configuration_text_form_data_provider:
    class: 'PrestaShop\Module\Myhealthbanner\Form\MyhealthbannerConfigurationTextFormDataProvider'
    arguments:
      - '@prestashop.module.myhealthbanner.form.myhealthbanner_text_data_configuration'

  prestashop.module.myhealthbanner.form.myhealthbanner_configuration_text_form_data_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\Handler'
    arguments:
      - '@form.factory'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.module.myhealthbanner.form.myhealthbanner_configuration_text_form_data_provider'
      - 'PrestaShop\Module\Myhealthbanner\Form\MyhealthbannerConfigurationFormType'
      - 'MyhealthbannerConfiguration'
